apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cp4ba-sa-rb
subjects:
- kind: ServiceAccount
  name: cp4ba-sa
  namespace: cp4ba
roleRef:
  kind: ClusterRole 
  name: cp4ba-cr
  apiGroup: rbac.authorization.k8s.io