kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c-db2-share
  namespace: db2
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: changeme
  volumeMode: Filesystem
