kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-argocd-cluster-argocd-application-controller-rhacm
rules:
  - apiGroups:
      - operator.open-cluster-management.io
    resources:
      - multiclusterhubs
    verbs:
      - update
      - create
      - list
      - delete
      - patch
 apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: db2-configure-cr
rules:
- apiGroups: [""] 
  resources: ["pods", "secrets"]
  verbs: ["get", "patch"]
- apiGroups: [""] 
  resources: ["pods/exec"]
  verbs: ["create"]