apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster }}-openldap-cp4ba
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster }}
spec:
  data:
    - secretKey: adminPassword
      remoteRef:
        key: 0678a623-77e9-1259-5b7c-3d9d4f32d0e3
    - secretKey: configPassword
      remoteRef:
        key: c1b66a6e-7e93-f212-89b1-6e7699cfeea9
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster }}-openldap-cp4ba
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        LDAP_ADMIN_PASSWORD: |-
          {{ "{{ .adminPassword | toString }}" }}
        LDAP_CONFIG_PASSWORD: |-
          {{ "{{ .configPassword | toString }}" }}
